#!/usr/bin/env bash

# Script that parse a movies directory and hunt alone files.
# Creates directories for every alone file and move this file into his directory.
# Mainly used to bring together movies and srt files into one and only directory.

set -o errexit
set -o pipefail

PROGRAME_NAME=$(basename "$0")

usage() {
    echo "Usage:"
    echo "  $PROGRAME_NAME [directory]"
}

error() {
    echo "Error: $1" 1>&2
    usage
    exit 1
}

main() {
    if [[ ! -d "$1" ]]; then
        error "$1 is not a directory."
    fi

    movies_dir="$1"

    for elem in "$movies_dir"/*; do
        if [[ -f "$elem" ]]; then
            bname=$(basename "$elem")
            dir="${bname%.*}"

            if [[ ! -e "$dir" ]]; then
                mkdir "${movies_dir}/${dir}"
            fi

            if [[ ! -f "$dir" ]]; then
                mv "${movies_dir}/${bname}" "${movies_dir}/${dir}"
            fi
        fi
    done
}

main "$@"
