#!/usr/bin/env bash

PROGRAME_NAME=$(basename "$0")

usage() {
    echo "Usage:"
    echo "  $PROGRAME_NAME [directory]"
}

error() {
    echo "Error: $1"
    usage
    exit 1
}

main() {
    if [[ ! -d "$1" ]]; then
        error "$1 is not a directory."
    fi

    movies_dir="$1"

    for elem in "$movies_dir"/*; do
        if [[ -f "$elem" ]]; then
            basename "$elem"
        fi
    done
}

main "$@"
